In [9]:
import pandas as pd
import re

In [28]:
# 경제
tmp1 = pd.read_csv('./teample_1_result/segye_economy_commonword_(2018.01.01 - 2018.03.31).csv', sep=(','), encoding='utf-8')
tmp2 = pd.read_csv('./teample_1_result/segye_economy_commonword_(2018.04.01 - 2018.06.30).csv', sep=(','), encoding ='utf-8')
tmp3 = pd.read_csv('./teample_1_result/segye_economy_commonword_(2018.07.01 - 2018.09.30).csv', sep=(','), encoding='utf-8')
tmp4 = pd.read_csv('./teample_1_result/segye_economy_commonword_(2018.10.01 - 2018.11.15).csv', sep=(','), encoding='utf-8')


# # 사회
# tmp1 = pd.read_csv('./teample_1_result/segye_society_commonword_(2018.01.01 - 2018.03.31).csv', sep=(','), encoding='utf-8')
# tmp2 = pd.read_csv('./teample_1_result/segye_society_commonword_(2018.04.01 - 2018.06.30).csv', sep=(','), encoding ='utf-8')
# tmp3 = pd.read_csv('./teample_1_result/segye_society_commonword_(2018.07.01 - 2018.09.30).csv', sep=(','), encoding='utf-8')
# tmp4 = pd.read_csv('./teample_1_result/segye_society_commonword_(2018.10.01 - 2018.11.15).csv', sep=(','), encoding='utf-8')


# # 정치
# tmp1 = pd.read_csv('./teample_1_result/segye_politics_commonword_(2018.01.01 - 2018.03.31).csv', sep=(','), encoding='utf-8')
# tmp2 = pd.read_csv('./teample_1_result/segye_politics_commonword_(2018.04.01 - 2018.06.30).csv', sep=(','), encoding ='utf-8')
# tmp3 = pd.read_csv('./teample_1_result/segye_politics_commonword_(2018.07.01 - 2018.09.30).csv', sep=(','), encoding='utf-8')
# tmp4 = pd.read_csv('./teample_1_result/segye_politics_commonword_(2018.10.01 - 2018.11.15).csv', sep=(','), encoding='utf-8')

#### 데이터프레임화

In [29]:
tmp1_df = pd.DataFrame(tmp1)
tmp2_df = pd.DataFrame(tmp2)
tmp3_df = pd.DataFrame(tmp3)
tmp4_df = pd.DataFrame(tmp4)

#### 불필요한 열 제거

In [30]:
tmp1_df.drop('Unnamed: 0',axis=1, inplace=True)
tmp2_df.drop('Unnamed: 0',axis=1, inplace=True)
tmp3_df.drop('Unnamed: 0',axis=1, inplace=True)
tmp4_df.drop('Unnamed: 0',axis=1, inplace=True)

#### 컬럼 명 변경

In [31]:
# 경제
tmp1_df.rename(columns={'단어명':'단어명', '빈도수':'빈도수'}, inplace=True)
tmp2_df.rename(columns={'단어명':'단어명', '빈도수':'빈도수'}, inplace=True)
tmp3_df.rename(columns={'단어명':'단어명', '빈도수':'빈도수'}, inplace=True)
tmp4_df.rename(columns={'단어명':'단어명', '빈도수':'빈도수'}, inplace=True)

# # 사회
# tmp1_df.rename(columns={'단어명':'단어명', '빈도수':'사회1분기빈도수'}, inplace=True)
# tmp2_df.rename(columns={'단어명':'단어명', '빈도수':'사회2분기빈도수'}, inplace=True)
# tmp3_df.rename(columns={'단어명':'단어명', '빈도수':'사회3분기빈도수'}, inplace=True)
# tmp4_df.rename(columns={'단어명':'단어명', '빈도수':'사회4분기빈도수'}, inplace=True)

# # 정치
# tmp1_df.rename(columns={'단어명':'단어명', '빈도수':'정치1분기빈도수'}, inplace=True)
# tmp2_df.rename(columns={'단어명':'단어명', '빈도수':'정치2분기빈도수'}, inplace=True)
# tmp3_df.rename(columns={'단어명':'단어명', '빈도수':'정치3분기빈도수'}, inplace=True)
# tmp4_df.rename(columns={'단어명':'단어명', '빈도수':'정치4분기빈도수'}, inplace=True)

#### 통째로 세로합치기

In [21]:
tmp2_df.head()
len(tmp2_df)

4638

In [25]:
df_append = tmp1_df.append(tmp2_df).append(tmp3_df).append(tmp4_df)
len(df_append)

17053

In [26]:
df_append.sort_values('빈도수', ascending=False)

        단어명  빈도수
0        삼성  114
0        가상  113
1        화폐  110
0        삼성   86
1      최저임금   82
2        톡톡   81
3        일상   79
2        지원   78
4        삼성   72
3       브리핑   72
4        경제   70
1       브리핑   70
2        금융   70
4        톡톡   69
5        투자   69
3        코노   69
6        인상   69
5       타이어   69
7        코노   68
7        금융   68
5        일상   68
6        대출   68
8       브리핑   68
8        코노   67
9        고용   64
11     최저임금   64
10       투자   64
9        금호   64
13       지원   62
12      일자리   62
...     ...  ...
3269     향년    1
3270     큰손    1
3271   성공사례    1
3272   노동시장    1
3273    칼텍스    1
3274    조원태    1
3275     직함    1
3276     옵션    1
3277    소신발    1
3260    구인회    1
3259     지다    1
3258     조문    1
3248     존경    1
3241   글로비스    1
3242     전성    1
3243     음매    1
3244     포천    1
3245    기업가    1
3246     비보    1
3247     애통    1
3249     남부    1
3257     조화    1
3250  재생에너지    1
3251    강신호    1
3252     산정    1
3253     어른    1
3254     정신    1
3255    경영인    1
3256     동업    1
3169     가분    1

[17053 rows x 2 columns]

In [ ]:
df_merge.to_csv('./teample_1_result/word_freq_df.csv', sep=(','), encoding='utf-8')

#### 중복 데이터 합치면서 결합하기

In [35]:
pd.merge(tmp1_df, tmp2_df, how='inner', on='단어명')

         단어명  빈도수_x  빈도수_y
0         가상    113     15
1         화폐    110     17
2         톡톡     81     69
3         일상     79     68
4         삼성     72    114
5        타이어     69      9
6         인상     69     38
7         코노     68     69
8        브리핑     68     70
9         금호     64      7
10        투자     64     33
11      최저임금     64     26
12       일자리     62     41
13        지원     62     49
14       김동연     59     52
15        시장     58     37
16        금융     57     70
17        해외     54     27
18        경영     51     21
19        롯데     50     25
20        금리     49     30
21        수출     48     37
22        관세     48     22
23        사업     47     35
24        최고     45     30
25        사회     44     13
26       플러스     43     37
27        산업     42     31
28        은행     42     23
29        매각     41     11
...      ...    ...    ...
2417  인베스트먼트      1      1
2418      부합      1      1
2419      부족      1      2
2420    카셰어링      1      1
2421     이노션      1      1
2422      대결      1      1
2423    카이스트      1      1
2424      연일      1      1
2425      꼬리      1      1
2426    미스터리      1      3
2427      수두      1      2
2428      주권      1      2
2429      반환      1      1
2430      방어      1      1
2431      등기      1      7
2432      관사      1      1
2433      조달      1      1
2434     거짓말      1      1
2435      자세      1      1
2436      불통      1      1
2437      분통      1      1
2438     이용자      1      1
2439      저녁      1      2
2440    신한은행      1      1
2441      홍콩      1      2
2442      몰이      1      1
2443     심상찮      1      1
2444      이직      1      1
2445      차례      1      2
2446      일터      1      1

[2447 rows x 3 columns]

In [33]:
? pd.merge

#### '단어명' 기준으로 병합

In [6]:
from functools import reduce
import pandas as pd
dfs = [tmp1_df, tmp2_df, tmp3_df, tmp4_df]
df_merge = reduce(lambda left, right: pd.merge(left, right, on='단어명'), dfs)

In [7]:
df_merge[:50]

       단어명  정치빈도수  경제빈도수  사회빈도수
0       남북    380     39     95
1       회담    278      6      6
2      김정은    263      1      8
3       평화    218      5    123
4       국회    209     23     44
5      민주당    209      5    117
6       평양    188     11     31
7       북한    181     26     61
8       선언    179      7     48
9       자유    167      5     64
10    정상회담    153      4     17
11      합의    130     24     52
12     위원장    128     27     54
13     비핵화    122      1      3
14      정상    110      5     18
15      국민    104     25     92
16     정의당     98      1     13
17      장관     94     36     48
18      선거     92      5    137
19     문재인     91     27     40
20     한반도     89      9     38
21      북미     89      6      5
22      대화     89     15     28
23      민주     85      3     80
24      고위     84      4     17
25     트럼프     84     32      2
26      여야     82      2     13
27      미국     81     79     35
28      평창     79     13     49
29      논란     77     86    186
30      보수     76     14     57
31      경제     76    116     35
32      공동     75     24     34
33      개헌     73      1     16
34      논의     72     26     35
35      대북     69      8     11
36      드루     69      5    115
37      방북     68      6      3
38      개혁     67     42     52
39      수사     67     18    337
40     이해찬     65      1      1
41      의혹     64     38    346
42    지방선거     64      3     55
43      협의     62     19     15
44      야당     59      2      9
45      발언     59      7     31
46    서울시장     59      1     12
47  남북정상회담     57      6     13
48      정당     56      2     28
49      회의     55     14     57

In [9]:
df_merge.to_csv('./teample_1_result/word_freq_df.csv', sep=(','), encoding='utf-8')

In [3]:
word_freq = pd.read_csv('./teample_1_result/word_freq_df.csv', sep=(','), encoding='utf-8')

In [4]:
word_freq

      Unnamed: 0   단어명  정치빈도수  경제빈도수  사회빈도수
0              0    남북    380     39     95
1              1    회담    278      6      6
2              2   김정은    263      1      8
3              3    평화    218      5    123
4              4    국회    209     23     44
5              5   민주당    209      5    117
6              6    평양    188     11     31
7              7    북한    181     26     61
8              8    선언    179      7     48
9              9    자유    167      5     64
10            10  정상회담    153      4     17
11            11    합의    130     24     52
12            12   위원장    128     27     54
13            13   비핵화    122      1      3
14            14    정상    110      5     18
15            15    국민    104     25     92
16            16   정의당     98      1     13
17            17    장관     94     36     48
18            18    선거     92      5    137
19            19   문재인     91     27     40
20            20   한반도     89      9     38
21            21    북미     89      6      5
22            22    대화     89     15     28
23            23    민주     85      3     80
24            24    고위     84      4     17
25            25   트럼프     84     32      2
26            26    여야     82      2     13
27            27    미국     81     79     35
28            28    평창     79     13     49
29            29    논란     77     86    186
...          ...   ...    ...    ...    ...
2803        2803   상반기      1     25      3
2804        2804    금고      1      4      2
2805        2805  비트코인      1     13      5
2806        2806    청렴      1      1      2
2807        2807    수급      1     10      6
2808        2808    공고      1      3      2
2809        2809    수호      1      3      6
2810        2810    코드      1      6      4
2811        2811    비교      1      9     35
2812        2812    무성      1      1      1
2813        2813    독자      1      4     13
2814        2814    산불      1      1     26
2815        2815    단절      1      2      1
2816        2816    문단      1      1      3
2817        2817   북새통      1      1      1
2818        2818   막바지      1      1      1
2819        2819    추징      1      3      6
2820        2820    절박      1      1      2
2821        2821    처가      1      2      2
2822        2822    페어      1      1      1
2823        2823    다소      1      1      1
2824        2824  무용지물      1      4      3
2825        2825   덩어리      1      1      1
2826        2826    분당      1      2      3
2827        2827    살이      1      3      9
2828        2828    건립      1      1     15
2829        2829   현충원      1      1      2
2830        2830   필요성      1      1      3
2831        2831    억제      1      2      3
2832        2832    지평      1      1      1

[2833 rows x 5 columns]

In [7]:
word_freq.drop('Unnamed: 0', axis=1, inplace=True)

In [9]:
word_freq['총빈도수'] = word_freq['정치빈도수'] + word_freq['경제빈도수'] + word_freq['사회빈도수']

In [13]:
word_freq.sort_values('총빈도수', ascending=False)

       단어명  정치빈도수  경제빈도수  사회빈도수  총빈도수
124     검찰     33     22    485   540
152     삼성     29    335    166   530
0       남북    380     39     95   514
173     경찰     26      8    466   500
41      의혹     64     38    346   448
50      단독     54    126    257   437
39      수사     67     18    337   422
61      인사     49     18    344   411
70      조사     44     66    265   375
29      논란     77     86    186   349
3       평화    218      5    123   346
5      민주당    209      5    117   331
159     재판     28      7    257   292
1       회담    278      6      6   290
4       국회    209     23     44   276
2      김정은    263      1      8   272
77      여성     41     26    204   271
7       북한    181     26     61   268
453     혐의     13     24    229   266
60      지원     49    111    104   264
769     인천      8      9    241   258
350     노조     16     54    185   255
646     법원      9     12    233   254
56     박근혜     50      5    192   247
72      최고     44     68    133   245
864   미세먼지      7     21    209   237
9       자유    167      5     64   236
96      채용     37     84    114   235
18      선거     92      5    137   234
8       선언    179      7     48   234
...    ...    ...    ...    ...   ...
2446    관장      1      1      1     3
2403    개보      1      1      1     3
2194    카이      1      1      1     3
2195    시아      1      1      1     3
2764  화재현장      1      1      1     3
2212   오르다      1      1      1     3
2217    스틸      1      1      1     3
2233   불합격      1      1      1     3
2755    사항      1      1      1     3
2238    고립      1      1      1     3
2241   메이커      1      1      1     3
2246    골든      1      1      1     3
2251    제대      1      1      1     3
2255    변질      1      1      1     3
2266    갈이      1      1      1     3
2281   무책임      1      1      1     3
2292    기분      1      1      1     3
2300  희망고문      1      1      1     3
2303    대국      1      1      1     3
2741    이득      1      1      1     3
2319    경감      1      1      1     3
2737    느낌      1      1      1     3
2327   조력자      1      1      1     3
2336    향수      1      1      1     3
2341    풍기      1      1      1     3
2354    유실      1      1      1     3
2358    밀당      1      1      1     3
2366    좇다      1      1      1     3
2723    열전      1      1      1     3
2832    지평      1      1      1     3

[2833 rows x 5 columns]