In [44]:
import pandas as pd
import re

In [45]:
# # 경제
# tmp1 = pd.read_csv('./teample_1_result/segye_economy_commonword_(2018.01.01 - 2018.03.31).csv', sep=(','), encoding='utf-8')
# tmp2 = pd.read_csv('./teample_1_result/segye_economy_commonword_(2018.04.01 - 2018.06.30).csv', sep=(','), encoding ='utf-8')
# tmp3 = pd.read_csv('./teample_1_result/segye_economy_commonword_(2018.07.01 - 2018.09.30).csv', sep=(','), encoding='utf-8')
# tmp4 = pd.read_csv('./teample_1_result/segye_economy_commonword_(2018.10.01 - 2018.11.15).csv', sep=(','), encoding='utf-8')


# # 사회
# tmp1 = pd.read_csv('./teample_1_result/segye_society_commonword_(2018.01.01 - 2018.03.31).csv', sep=(','), encoding='utf-8')
# tmp2 = pd.read_csv('./teample_1_result/segye_society_commonword_(2018.04.01 - 2018.06.30).csv', sep=(','), encoding ='utf-8')
# tmp3 = pd.read_csv('./teample_1_result/segye_society_commonword_(2018.07.01 - 2018.09.30).csv', sep=(','), encoding='utf-8')
# tmp4 = pd.read_csv('./teample_1_result/segye_society_commonword_(2018.10.01 - 2018.11.15).csv', sep=(','), encoding='utf-8')


# 정치
tmp1 = pd.read_csv('./teample_1_result/segye_politics_commonword_freq_sorted_df.csv', sep=(','), encoding='utf-8')
tmp2 = pd.read_csv('./teample_1_result/chosun_politics_commonword_(2018-01-01 - 2018-11-15).csv', sep=(','), encoding ='utf-8')
tmp3 = pd.read_csv('./teample_1_result/hankyure_politics_commonword_(2018-01-01 - 2018-11-15).csv', sep=(','), encoding='utf-8')
# tmp4 = pd.read_csv('./teample_1_result/segye_politics_commonword_(2018.10.01 - 2018.11.15).csv', sep=(','), encoding='utf-8')

#### 데이터프레임화

In [46]:
tmp1_df = pd.DataFrame(tmp1)
tmp2_df = pd.DataFrame(tmp2)
tmp3_df = pd.DataFrame(tmp3)
# tmp4_df = pd.DataFrame(tmp4)

In [47]:
tmp3_df.head()

   Unnamed: 0  단어명  빈도수
0           0   남북  380
1           1   회담  278
2           2  김정은  263
3           3   평화  218
4           4  홍준표  218

#### 불필요한 열 제거

In [48]:
tmp1_df.drop('Unnamed: 0',axis=1, inplace=True)
tmp1_df.drop('정치1분기빈도수',axis=1, inplace=True)
tmp1_df.drop('정치2분기빈도수',axis=1, inplace=True)
tmp1_df.drop('정치3분기빈도수',axis=1, inplace=True)
tmp1_df.drop('정치4분기빈도수',axis=1, inplace=True)

tmp2_df.drop('Unnamed: 0',axis=1, inplace=True)
# tmp2_df.drop('정치1분기빈도수',axis=1, inplace=True)
# tmp2_df.drop('정치2분기빈도수',axis=1, inplace=True)
# tmp2_df.drop('정치3분기빈도수',axis=1, inplace=True)
# tmp2_df.drop('정치4분기빈도수',axis=1, inplace=True)

tmp3_df.drop('Unnamed: 0',axis=1, inplace=True)
# tmp3_df.drop('정치1분기빈도수',axis=1, inplace=True)
# tmp3_df.drop('정치2분기빈도수',axis=1, inplace=True)
# tmp3_df.drop('정치3분기빈도수',axis=1, inplace=True)
# tmp3_df.drop('정치4분기빈도수',axis=1, inplace=True)

In [49]:
tmp3_df.head()

   단어명  빈도수
0   남북  380
1   회담  278
2  김정은  263
3   평화  218
4  홍준표  218

#### 컬럼 명 변경

In [50]:
# # 경제
# tmp1_df.rename(columns={'단어명':'단어명', '빈도수':'경제1분기빈도수'}, inplace=True)
# tmp2_df.rename(columns={'단어명':'단어명', '빈도수':'경제2분기빈도수'}, inplace=True)
# tmp3_df.rename(columns={'단어명':'단어명', '빈도수':'경제3분기빈도수'}, inplace=True)
# tmp4_df.rename(columns={'단어명':'단어명', '빈도수':'경제4분기빈도수'}, inplace=True)

# # 사회
# tmp1_df.rename(columns={'단어명':'단어명', '빈도수':'사회1분기빈도수'}, inplace=True)
# tmp2_df.rename(columns={'단어명':'단어명', '빈도수':'사회2분기빈도수'}, inplace=True)
# tmp3_df.rename(columns={'단어명':'단어명', '빈도수':'사회3분기빈도수'}, inplace=True)
# tmp4_df.rename(columns={'단어명':'단어명', '빈도수':'사회4분기빈도수'}, inplace=True)

# 정치
tmp1_df.rename(columns={'단어명':'단어명', '총빈도수':'세계빈도수'}, inplace=True)
tmp2_df.rename(columns={'단어명':'단어명', '정치 빈도수':'조선빈도수'}, inplace=True)
tmp3_df.rename(columns={'단어명':'단어명', '빈도수':'한겨레빈도수'}, inplace=True)
# tmp4_df.rename(columns={'단어명':'단어명', '빈도수':'정치4분기빈도수'}, inplace=True)

#### '단어명' 기준으로 병합

In [51]:
from functools import reduce
import pandas as pd
dfs = [tmp1_df, tmp2_df, tmp3_df]
word_freq = reduce(lambda left, right: pd.merge(left, right, on='단어명'), dfs)

In [53]:
word_freq[:10]

   단어명  세계빈도수  조선빈도수  한겨레빈도수
0  홍준표    344    266     218
1   민주    306     59      85
2   국회    297    284     209
3   여야    243    130      82
4  민주당    238    222     209
5   드루    231    171      69
6   남북    225    501     380
7   수사    220     79      67
8   국민    220    125     104
9   평화    216    200     218

In [54]:
# # 경제
# word_freq['총빈도수'] = word_freq['경제1분기빈도수'] + word_freq['경제2분기빈도수'] + word_freq['경제3분기빈도수'] + word_freq['경제4분기빈도수']

# # 사회
# word_freq['총빈도수'] = word_freq['사회1분기빈도수'] + word_freq['사회2분기빈도수'] + word_freq['사회3분기빈도수'] + word_freq['사회4분기빈도수']


# 정치
word_freq['총빈도수'] = word_freq['세계빈도수'] + word_freq['조선빈도수'] + word_freq['한겨레빈도수']

In [55]:
word_freq = word_freq.sort_values('총빈도수', ascending=False)

In [56]:
word_freq

      단어명  세계빈도수  조선빈도수  한겨레빈도수  총빈도수
6      남북    225    501     380  1106
28    김정은    131    682     263  1076
17     회담    174    494     278   946
0     홍준표    344    266     218   828
2      국회    297    284     209   790
4     민주당    238    222     209   669
9      평화    216    200     218   634
14     선언    190    259     179   628
48    비핵화     94    370     122   586
42   정상회담    102    288     153   543
70    트럼프     77    362      84   523
49     평양     93    230     188   511
115    북한     60    270     181   511
10    김성태    211    183     104   498
19    안철수    171    189     126   486
5      드루    231    171      69   471
3      여야    243    130      82   455
1      민주    306     59      85   450
8      국민    220    125     104   449
44     합의    100    206     130   436
16     선거    179    139      92   410
21   지방선거    163    177      64   404
11     의혹    210    128      64   402
68    판문점     78    180     138   396
22     논란    151    162      77   390
46     장관     99    197      94   390
26     경제    142    166      76   384
20     출마    171    110      90   371
12    이재명    205    121      40   366
7      수사    220     79      67   366
..    ...    ...    ...     ...   ...
925    미소      6      2       3    11
881    트랙      7      3       1    11
901    편성      6      3       2    11
891    납득      7      2       2    11
962    급증      4      4       3    11
898   라운드      7      1       3    11
942    명분      5      5       1    11
869   김명수      7      1       2    10
857    발족      7      2       1    10
974   제자리      4      3       3    10
926   표창원      6      2       2    10
854    비율      7      2       1    10
959    출연      4      5       1    10
947    취급      5      3       2    10
930    번지      6      3       1    10
910   저출산      6      3       1    10
946   그림자      5      3       2    10
956   전교조      5      3       1     9
933    퇴진      6      2       1     9
939    돼지      5      3       1     9
945    본질      5      1       3     9
963    적절      4      3       2     9
953    몰카      5      3       1     9
966    날개      4      2       2     8
972    추측      4      3       1     8
964    인연      4      1       3     8
919    단호      6      1       1     8
975   금태섭      4      1       3     8
968    보전      4      1       2     7
965    편의      4      2       1     7

[978 rows x 5 columns]

In [57]:
# # 경제
# word_freq.to_csv('./teample_1_result/segye_economy_commonword_freq_sorted_df.csv', sep=(','), encoding='utf-8')

# # 사회
# word_freq.to_csv('./teample_1_result/segye_society_commonword_freq_sorted_df.csv', sep=(','), encoding='utf-8')

# 정치
word_freq.to_csv('./teample_1_result/all_politics_commonword_freq_sorted_df.csv', sep=(','), encoding='utf-8')